import test from 'node:test';
import assert from 'node:assert/strict';
import Stripe from 'stripe';
import {createPaymentService,settlementAmounts} from '../server/payments.mjs';
import {paymentConfiguration,portalConfig} from '../server/portal-config.mjs';
import {quotePlacement,PAYMENT_TERMS_VERSION} from '../portal/payments.mjs';
import {filterListings,newRace} from '../portal/model.mjs';
const id='10000000-0000-0000-0000-000000000001',sponsor='10000000-0000-0000-0000-000000000002',athlete='10000000-0000-0000-0000-000000000003';
const env={APP_URL:'https://enduur.co',SUPABASE_URL:'https://example.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'server-only',STRIPE_SECRET_KEY:'sk_test_example',STRIPE_WEBHOOK_SECRET:'whsec_example',CRON_SECRET:'x'.repeat(32),PAYMENT_ADMIN_USER_IDS:athlete,PAYMENTS_ENABLED:'true',RESEND_API_KEY:'re_example'};
const request=(p,token='valid',origin=env.APP_URL)=>new Request(env.APP_URL+'/api/payments',{method:'POST',headers:{Authorization:'Bearer '+token,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(p)});
function fixture(overrides={}){
 const now=Date.now(),calls=[];
 const v={booking_id:id,sponsor_id:sponsor,athlete_id:athlete,state:'unpaid',booking_status:'accepted',athlete_cents:10000,total_cents:12000,currency:'usd',checkout_key:'key',checkout_created_at:new Date(now).toISOString(),checkout_expires_at:new Date(now+3600000).toISOString(),checkout_session:null,payment_intent:'pi_test',charge_id:'ch_test',stripe_account:'acct_test',event_name:'Test race',operation_at:new Date(now).toISOString(),operation_key:'op',earned_cents:10000,livemode:false,...overrides};
 const session={id:'cs_test',mode:'payment',livemode:false,payment_status:'unpaid',status:'open',url:'https://checkout.stripe.com/example',client_reference_id:id,metadata:{booking_id:id},amount_total:12000,currency:'usd',payment_intent:'pi_test'};
 const charge={id:'ch_test',amount:12000,amount_refunded:0,currency:'usd',payment_intent:'pi_test',disputed:false};
 const pi={id:'pi_test',livemode:false,status:'succeeded',amount_received:12000,currency:'usd',latest_charge:'ch_test',metadata:{booking_id:id}};
 const transfers=new Map(),refunds=new Map();let loseTransferResponse=false;
 const db={auth:{getUser:async token=>({data:{user:token==='valid'?{id:sponsor,email:'test@example.com'}:token==='admin'?{id:athlete}:null}})},rpc:async(name,{action,p})=>{
  calls.push({action,p});if(action==='queue')return {data:[{booking_id:id,state:v.state}]};
  if(action==='checkout-save')v.checkout_session=p.session;
  if(action==='paid')v.state='paid';
  if(action==='stripe-issue'){v.state='disputed';v.issue=p.reason;}
  if(action==='settle-claim'){if(!['release_ready','processing'].includes(v.state))return {error:{message:'Not eligible'}};v.state='processing';}
  if(action==='refund-record'){v.refund_id=p.refund;v.refund_cents=p.amount;}
  if(action==='settled'){v.state=v.earned_cents===0?'refunded':v.refund_cents?'partially_refunded':'released';v.transfer_id=p.transfer;}
  if(action==='expire')v.state='expired';
  return {data:structuredClone(v)};
 }};
 const stripe={accounts:{retrieve:async()=>({country:'US',details_submitted:true,payouts_enabled:true,capabilities:{transfers:'active'}})},checkout:{sessions:{create:async(params,opts)=>{calls.push({action:'stripe-checkout',params,opts});return {...session};},retrieve:async()=>({...session}),expire:async()=>({...session,status:'expired'})}},paymentIntents:{retrieve:async()=>({...pi})},charges:{retrieve:async()=>({...charge})},transfers:{create:async(params,opts)=>{calls.push({action:'stripe-transfer',params,opts});if(!transfers.has(opts.idempotencyKey))transfers.set(opts.idempotencyKey,{id:'tr_test',...params});if(loseTransferResponse){loseTransferResponse=false;throw Error('Network response lost');}return transfers.get(opts.idempotencyKey);}},refunds:{create:async(params,opts)=>{calls.push({action:'stripe-refund',params,opts});const refund={id:'re_test',status:'succeeded',...params};refunds.set(refund.id,refund);charge.amount_refunded=params.amount;return refund;},retrieve:async rid=>refunds.get(rid),list:async()=>({data:[...refunds.values()]})},webhooks:Stripe.webhooks};
 return {v,session,pi,charge,calls,stripe,db,transfers,refunds,loseTransfer:()=>{loseTransferResponse=true;},service:createPaymentService(env,{stripe,db,now:()=>now})};
}
test('20% markup preserves $100 payout and totals $120 without altering calculator',()=>{assert.deepEqual(quotePlacement(100),{athleteCents:10000,markupCents:2000,sponsorCents:12000,currency:'usd'});assert.equal(quotePlacement(101).sponsorCents,12120);assert.equal(PAYMENT_TERMS_VERSION,'2026-10-02');assert.deepEqual(settlementAmounts(10000,12000,7000),{athleteCents:7000,refundCents:3600});assert.deepEqual(settlementAmounts(10000,12000,0),{athleteCents:0,refundCents:12000});for(const value of [-1,10001,NaN])assert.throws(()=>settlementAmounts(10000,12000,value));});
test('sponsor budget filter uses the actual all-in price',()=>{const r={...newRace(),race_date:'2099-01-01',status:'published',asking_price:100,placements:['chest'],reserved:[],profile:{}};assert.equal(filterListings([r],{budget:100}).length,0);assert.equal(filterListings([r],{budget:120}).length,1);});
test('configuration is disabled without complete setup and explicit live approval',async()=>{assert.equal(paymentConfiguration({}).enabled,false);assert.equal(paymentConfiguration(env).enabled,true);for(const key of ['CRON_SECRET','STRIPE_WEBHOOK_SECRET','PAYMENT_ADMIN_USER_IDS','SUPABASE_SERVICE_ROLE_KEY'])assert.equal(paymentConfiguration({...env,[key]:''}).enabled,false);assert.equal(paymentConfiguration({...env,STRIPE_SECRET_KEY:'sk_live_example'}).enabled,false);const config=await portalConfig({...env,SUPABASE_PUBLISHABLE_KEY:'sb_publishable_example'}).json();assert.equal(config.payments.enabled,true);assert.ok(!JSON.stringify(config).includes('server-only'));assert.ok(!JSON.stringify(config).includes('sk_test_'));});
test('checkout rejects unauthenticated, wrong-origin and wrong-owner requests',async()=>{const f=fixture();assert.equal((await f.service.handle(request({action:'checkout',id},'bad'))).status,401);assert.equal((await f.service.handle(request({action:'checkout',id},'valid','https://bad.example'))).status,403);f.v.sponsor_id=athlete;assert.equal((await f.service.handle(request({action:'checkout',id}))).status,403);assert.ok(!f.calls.some(c=>c.action==='stripe-checkout'));});
test('Checkout ignores browser prices and uses a stable idempotency key and deadline',async()=>{const f=fixture();const response=await f.service.handle(request({action:'checkout',id,total_cents:1,athlete_id:sponsor}));assert.equal(response.status,200);const call=f.calls.find(c=>c.action==='stripe-checkout');assert.equal(call.params.line_items[0].price_data.unit_amount,12000);assert.equal(call.params.expires_at,Math.floor(Date.parse(f.v.checkout_expires_at)/1000));assert.equal(call.opts.idempotencyKey,'enduur-checkout-key');assert.equal(f.v.state,'unpaid');});
test('a redirect or incomplete Checkout cannot assert payment',async()=>{const f=fixture();f.v.checkout_session=f.session.id;assert.equal(await f.service.reconcile(f.session),false);assert.equal(f.v.state,'unpaid');f.session.payment_status='paid';f.pi.amount_received=1;await assert.rejects(()=>f.service.reconcile(f.session),/verification/);assert.equal(f.v.state,'unpaid');});
test('verified payment requires session identity, currency, mode and amount',async()=>{const f=fixture();f.v.checkout_session=f.session.id;f.session.payment_status='paid';for(const change of [{id:'cs_other'},{amount_total:1},{currency:'eur'}])await assert.rejects(()=>f.service.reconcile({...f.session,...change}),/verification/);assert.equal(await f.service.reconcile({...f.session,livemode:true}),false);await f.service.reconcile(f.session);assert.equal(f.v.state,'paid');await f.service.reconcile(f.session);assert.equal(f.v.state,'paid');});
test('webhook requires a valid signature and can safely replay verified events',async()=>{const f=fixture();f.v.checkout_session=f.session.id;f.session.payment_status='paid';const payload=JSON.stringify({id:'evt_test',livemode:false,type:'checkout.session.completed',data:{object:f.session}});const signed=()=>new Request(env.APP_URL+'/api/stripe-webhook',{method:'POST',headers:{'stripe-signature':Stripe.webhooks.generateTestHeaderString({payload,secret:env.STRIPE_WEBHOOK_SECRET})},body:payload});assert.equal((await f.service.webhook(new Request(env.APP_URL,{method:'POST',body:payload}))).status,400);assert.equal((await f.service.webhook(signed())).status,200);assert.equal((await f.service.webhook(signed())).status,200);assert.equal(f.v.state,'paid');});
test('full approval transfers exactly the athlete amount and records settlement',async()=>{const f=fixture({state:'release_ready'});await f.service.settle(id);assert.equal(f.v.state,'released');assert.equal(f.transfers.size,1);assert.equal([...f.transfers.values()][0].amount,10000);assert.equal([...f.transfers.values()][0].source_transaction,'ch_test');assert.equal(f.refunds.size,0);});
test('lost transfer response retries the same operation without another transfer',async()=>{const f=fixture({state:'release_ready'});f.loseTransfer();await assert.rejects(()=>f.service.settle(id),/Network/);assert.equal(f.v.state,'processing');await f.service.settle(id);assert.equal(f.transfers.size,1);assert.equal(f.v.state,'released');});
test('partial delivery refunds $36 and transfers $70 once',async()=>{const f=fixture({state:'release_ready',earned_cents:7000});await f.service.settle(id);assert.equal(f.v.state,'partially_refunded');assert.equal(f.v.refund_cents,3600);assert.equal([...f.transfers.values()][0].amount,7000);});
test('full cancellation refunds all $120 and creates no athlete transfer',async()=>{const f=fixture({state:'release_ready',earned_cents:0});await f.service.settle(id);assert.equal(f.v.state,'refunded');assert.equal(f.v.refund_cents,12000);assert.equal(f.transfers.size,0);});
test('disputed charges and unexpected refunds prevent transfers',async()=>{for(const change of [{disputed:true},{amount_refunded:100}]){const f=fixture({state:'release_ready'});Object.assign(f.charge,change);await f.service.settle(id);assert.equal(f.transfers.size,0);assert.equal(f.v.state,'disputed');}});
test('stale unknown operations require reconciliation rather than duplicate money movements',async()=>{const f=fixture({state:'processing',operation_at:new Date(Date.now()-25*3600000).toISOString()});await f.service.settle(id);assert.equal(f.v.state,'disputed');assert.equal(f.transfers.size,0);const c=fixture({checkout_created_at:new Date(Date.now()-25*3600000).toISOString()});await assert.rejects(()=>c.service.checkout(id,{id:sponsor}),/reconciliation/);assert.ok(!c.calls.some(c=>c.action==='stripe-checkout'));});
test('admin decisions and cron execution cannot be invoked by normal users',async()=>{const f=fixture();assert.equal((await f.service.handle(request({action:'resolve',id,earned_cents:0,reason:'Arbitrary refund attempt.'}))).status,403);assert.equal((await f.service.cron(new Request(env.APP_URL+'/api/payments-cron'))).status,401);});
test('failed proof emails never start the 72-hour timer; accepted emails do',async()=>{
 for(const ok of [false,true]){
  const f=fixture({state:'review'}),sent=[];
  const db={auth:{admin:{getUserById:async()=>({data:{user:{email:'test@example.com'}}})}},rpc:async(name,{action,p})=>{if(action==='notification-queue')return {data:[{booking_id:id,recipient:sponsor,kind:'proof'}]};if(action==='notification-sent')sent.push(p);return {data:f.v};}};
  const service=createPaymentService(env,{stripe:f.stripe,db,fetchImpl:async(url,opts)=>{assert.equal(url,'https://api.resend.com/emails');assert.ok(JSON.parse(opts.body).text.includes('72 hours'));assert.equal(opts.headers['Idempotency-Key'],`enduur-${id}-proof-${sponsor}`);return new Response('{}',{status:ok?200:503});}});
  const result=await service.notifyParticipants();assert.equal(result[0].ok,ok);assert.equal(sent.length,ok?1:0);
 }
});
