import {currency,paymentLabels,bookingRules,PAYMENT_TERMS_VERSION,quotePlacement} from './payments.mjs';
import {escapeHtml as e,dateLabel,placementInfo,safeProofUrl} from './model.mjs';
const btn=(label,action,id='',extra='')=>`<button type="button" class="button outline" data-action="${action}" data-id="${e(id)}" ${extra}>${label}</button>`;
const date=value=>value?e(new Date(value).toLocaleString()):'—';
export const rulesMarkup=()=>`<div class="payment-rules">${bookingRules.map(([title,copy])=>`<p><strong>${e(title)}.</strong> ${e(copy)}</p>`).join('')}</div>`;
export const termsCheckbox=()=>`<label class="check"><input type="checkbox" name="terms_version" value="${PAYMENT_TERMS_VERSION}" required>I agree to the <a href="/payment-terms.html" target="_blank" rel="noopener">booking and payment rules ↗</a>, the price, artwork instructions, deliverables, and allocation shown here.</label>`;
export function allocationMarkup(amount,share=70){const placement=Math.round(amount*share/100);return `<p class="help">Agreed package allocation: ${currency(placement)} for race placement and photo proof; ${currency(amount-placement)} for social content. These values guide any partial-delivery review.</p>`;}
export function requestCards(rows,{athlete,demo,enabled,payments=[]}){
 return `<div class="request-list">${rows.map(b=>{
 const p=payments.find(p=>p.booking_id===b.id),c=b.contract,r=b.listing,active=['accepted','submitted','completed'].includes(b.status);
 const price=c?currency(athlete?c.athlete_cents:c.total_cents):currency(b.price*100);
 const controls=[];
 if(b.status==='pending'){
  if(athlete){if(c)controls.push(btn('Accept partnership','transition',b.id,`data-status="accepted" ${!enabled&&!demo?'disabled':''}`));controls.push(btn('Decline','transition',b.id,'data-status="declined"'));}
  else controls.push(btn('Cancel request','transition',b.id,'data-status="cancelled"'));
 }
 if(p&&active){
  if(p.state==='unpaid'&&!athlete)controls.push(btn(demo?'Simulate sponsor payment':'Pay '+price,'checkout',b.id,!enabled&&!demo?'disabled':''));
  if(p.state==='unpaid'&&!demo)controls.push(btn('Check payment status','sync-payment',b.id,!enabled?'disabled':''));
  if(p.state==='paid'&&athlete){if(c.preapproval)controls.push(btn('Submit content draft','draft-dialog',b.id));controls.push(btn('Submit event proof','proof-dialog',b.id));}
  if(p.state==='paid'&&!athlete&&p.draft_url&&!p.draft_approved_at)controls.push(btn('Approve content draft','approve-draft',b.id));
  if(p.state==='review'&&!athlete)controls.push(btn('Approve proof & release payout','transition',b.id,'data-status="completed"'));
  if(['paid','review'].includes(p.state))controls.push(btn('Report issue / cancellation','issue-dialog',b.id));
 }
 controls.push(btn('Preview on athlete','partnership-preview',b.id),btn('Download brief','download-brief',b.id));
 return `<article class="request-card"><div class="request-top"><div><span class="tag">${e(b.status.toUpperCase())}</span><h3>${e(b.brand_name)} × ${e(r.event_name)}</h3></div><div class="request-price"><strong>${price}</strong><div class="small">${c?athlete?'Your agreed payout':'Sponsor total':'Legacy agreed price'}</div></div></div><p>${e(r.location)} · ${dateLabel(r.race_date)} · ${e(placementInfo(b.placement,r.outfit).label)}</p><p>${e(b.deliverables)}</p>${b.message?`<blockquote>${e(b.message)}</blockquote>`:''}${c?`<p><strong>Artwork:</strong> ${e(c.artwork_spec)}</p>${allocationMarkup(athlete?c.athlete_cents:c.total_cents,Math.round(c.placement_cents/c.athlete_cents*100))}<p class="help">${c.preapproval?'Sponsor approval is required before publishing social content.':'No pre-publication approval required.'} <a href="/payment-terms.html" target="_blank" rel="noopener">Booking rules ↗</a></p>`:'<p class="form-notice">This request predates checkout and has no payment record. Agree a new booking to pay through enduur; this history does not confirm payment.</p>'}${p?`<div class="payment-status"><strong>${demo?'DEMO · ':p.livemode===false?'STRIPE TEST · ':''}${e(paymentLabels[p.state]||p.state)}</strong>${p.state==='unpaid'&&b.status==='pending'?'<p>The athlete has not accepted yet. No payment is due.</p>':''}${p.state==='unpaid'&&p.pay_by?`<p>Pay by ${date(p.pay_by)}. Work starts after payment is secured.</p>`:''}${p.state==='paid'?`<p>Complete proof due ${date(p.proof_due)}.</p>`:''}${p.state==='review'?`<p>${p.review_by?'Review by '+date(p.review_by)+'.':'Email notification pending; the 72-hour deadline has not started.'} Approval or no timely objection makes payout eligible for release.</p>`:''}${p.issue?`<p>${e(p.issue)}</p>`:''}${p.resolution_note?`<p><strong>Resolution:</strong> ${e(p.resolution_note)}</p>`:''}${p.refund_cents?`<p>Sponsor refund: ${currency(p.refund_cents)}</p>`:''}${p.earned_cents!=null&&['released','partially_refunded','refunded'].includes(p.state)?`<p>${athlete?'Amount sent to your Stripe account':'Athlete earned'}: ${currency(p.earned_cents)}. Bank arrival follows Stripe’s payout schedule.</p>`:''}</div>`:''}${p?.draft_url?`<p><a href="${e(safeProofUrl(p.draft_url)||'#')}" target="_blank" rel="noopener">Review content draft ↗</a> · ${p.draft_approved_at?'Approved':'Awaiting approval'}</p>`:''}${b.proof_url?`<p><a href="${e(safeProofUrl(b.proof_url)||'#')}" target="_blank" rel="noopener">View event proof ↗</a></p><p>${e(b.proof_note||'')}</p>`:''}<div class="inline-actions">${controls.join('')}</div>${!enabled&&!demo&&c?'<p class="help">Payment launch is being prepared. Requests can be sent, but acceptance and checkout are not open yet.</p>':''}</article>`;
 }).join('')}</div>`;
}
export function payoutPanel({demo,enabled,mode,accounts=[]}){
 const a=accounts.find(a=>a.livemode===(mode==='live'));
 return `<div class="panel"><span class="mono">US ATHLETES · USD</span><h2>Your earnings. Your bank account.</h2><p>Connect your US payout account securely with Stripe. Identity and bank details are entered on Stripe’s hosted setup page.</p><p class="form-notice">${demo?'Demo only. No bank account is connected and no money moves.':!enabled?'Payout setup will open when enduur’s Stripe account is connected.':mode==='test'?'Stripe test mode. Use test details only. No real money moves.':a?.ready?'Your payout account is ready.':'Finish payout setup before accepting a paid partnership.'}</p>${enabled&&!demo?`<div class="inline-actions">${btn(a?.ready?'Update payout details':'Set up payouts','onboard')}${btn('Check setup status','account-status')}${a?.ready?btn('Open Stripe dashboard','stripe-dashboard'):''}</div>`:''}<p class="help">A $100 requested placement pays you $100 when all agreed work is delivered. The sponsor sees the full booking price. Enduur covers Stripe processing costs from its share.</p><p class="help">For this pilot, accept bookings 1–30 days before the race. Sponsors have up to 48 hours to pay, ending before race day.</p></div><details class="panel"><summary>How payment and proof work</summary>${rulesMarkup()}</details>`;
}
export function demoContract(r,p){const q=quotePlacement(r.asking_price),placement=Math.round(q.athleteCents*(r.placement_share??70)/100);return {version:PAYMENT_TERMS_VERSION,athlete_cents:q.athleteCents,total_cents:q.sponsorCents,placement_cents:placement,social_cents:q.athleteCents-placement,artwork_spec:p.artwork_spec,preapproval:!!p.preapproval,race_date:r.race_date,deliverables:r.deliverables};}
