import {raceTypes,escapeHtml as e} from './model.mjs';
export const rankingTypes=['Overall','Gender','Age group','Division'];
export const maxPerformances=12;
export function validateMeasurements(p){for(const [key,min,max,label] of [['height_cm',80,260,'height'],['weight_kg',25,350,'weight']]){const n=p[key];if(n!==null&&n!==undefined&&n!==''&&(!Number.isFinite(Number(n))||Number(n)<min||Number(n)>max))throw new Error(`Enter a valid ${label} (${min}–${max} ${key==='height_cm'?'cm':'kg'}).`);}}
export function validatePerformance(p,{pending=false}={}){
 for(const [key,max,label] of [['event_name',120,'event name'],['location',120,'race location'],['distance',100,'distance or format']])if(typeof p[key]!=='string'||!p[key].trim()||p[key].length>max)throw new Error(`Add a ${label} (up to ${max} characters).`);
 if(!Object.hasOwn(raceTypes,p.discipline))throw new Error('Choose a race discipline.');
 if(!Number.isInteger(p.year)||p.year<1950||p.year>new Date().getFullYear())throw new Error('Choose the year of a completed race.');
 if(!Number.isInteger(p.place)||p.place<1||p.place>1000000)throw new Error('Enter a placing of 1 or higher.');
 if(!rankingTypes.includes(p.ranking))throw new Error('Choose what the placing represents.');
 if((p.division||'').length>100||(p.ranking!=='Overall'&&!p.division?.trim()))throw new Error('Name the category or division for this placing.');
 if(p.field_size!==null&&p.field_size!==undefined&&(!Number.isInteger(p.field_size)||p.field_size<p.place||p.field_size>1000000))throw new Error('Field size must be at least your placing, within the same category.');
 if((p.finish_time||'')&&!/^\d{1,3}:[0-5]\d:[0-5]\d$/.test(p.finish_time))throw new Error('Use H:MM:SS for finish time, such as 1:12:35.');
 if(!p.evidence_path&&!(pending&&p.evidence_file))throw new Error('Attach a results screenshot, podium photo or event photo for this result.');
 return p;
}
export function validatePerformances(rows,options){if(!Array.isArray(rows)||rows.length>maxPerformances)throw new Error('Add up to 12 past results.');const ids=new Set();for(const row of rows){if(!row.id||ids.has(row.id))throw new Error('Results must have distinct IDs.');ids.add(row.id);validatePerformance(row,options);}}
export function performanceSummary(r){return `#${r.place}${r.field_size?' of '+r.field_size.toLocaleString():''} · ${r.ranking}${r.division?' — '+r.division:''}`;}
export function measurementsLabel(p){return [p.height_cm?`${Number(p.height_cm).toLocaleString()} cm`:'',p.weight_kg?`${Number(p.weight_kg).toLocaleString()} kg`:''].filter(Boolean).join(' · ');}
export function performanceCards(rows=[],{editable=false,owner=''}={}){return rows.length?`<div class="performance-list">${[...rows].sort((a,b)=>b.year-a.year).map(r=>`<article class="performance-card"><div><span class="mono">${e(r.discipline)} / ${e(r.year)}</span><h3>${e(r.event_name)}</h3><p>${e(r.location)} · ${e(r.distance)}</p><strong>${e(performanceSummary(r))}</strong>${r.finish_time?`<p>Finish time · ${e(r.finish_time)}</p>`:''}<span class="evidence-tag">Evidence attached · athlete supplied</span></div><div class="inline-actions"><button type="button" class="text-button" data-action="performance-evidence" data-id="${e(r.id)}" data-owner="${e(owner)}">View evidence ↗</button>${editable?`<button type="button" class="text-button" data-action="performance-edit" data-id="${e(r.id)}">Edit result</button><button type="button" class="text-button" data-action="performance-remove" data-id="${e(r.id)}">Remove result</button>`:''}</div></article>`).join('')}</div>`:'<p class="help">No past results shared yet.</p>';}
export function performanceForm(r={}){const opts=(items,value)=>items.map(v=>`<option ${v===value?'selected':''}>${e(v)}</option>`).join('');return `<form id="performance-form"><input type="hidden" name="result_id" value="${e(r.id||'')}"><p class="modal-copy">Share a completed race and an image that supports your result. Sponsors can review the evidence alongside your upcoming races.</p><div class="fields"><label class="field full">Past event name<input name="event_name" required maxlength="120" value="${e(r.event_name)}" placeholder="e.g. HYROX Milan"></label><label class="field">Race year<input name="year" type="number" min="1950" max="${new Date().getFullYear()}" required value="${e(r.year||'')}" placeholder="2024"></label><label class="field">Past race location<input name="location" required maxlength="120" value="${e(r.location)}" placeholder="Milan, Italy"></label><label class="field">Race discipline<select name="discipline">${opts(Object.keys(raceTypes),r.discipline||'HYROX')}</select></label><label class="field">Distance or format<input name="distance" required maxlength="100" value="${e(r.distance)}" placeholder="e.g. Singles Open / Olympic triathlon"></label><label class="field">Placing<input name="place" type="number" required min="1" max="1000000" value="${e(r.place||'')}" placeholder="5"></label><label class="field">Placing type<select name="ranking">${opts(rankingTypes,r.ranking||'Overall')}</select></label><label class="field full">Category / division<input name="division" maxlength="100" value="${e(r.division)}" placeholder="e.g. Men’s Open / Women 30–34"></label><label class="field">Field size (optional)<input name="field_size" type="number" min="1" max="1000000" value="${e(r.field_size||'')}" placeholder="Same ranking category"></label><label class="field">Finish time (optional)<input name="finish_time" maxlength="9" value="${e(r.finish_time)}" placeholder="1:12:35"></label></div><label class="field">${r.evidence_path||r.evidence_file?'Replace evidence image (optional)':'Evidence image (required)'}<input name="evidence" type="file" accept="image/jpeg,image/png,image/webp" ${r.evidence_path||r.evidence_file?'':'required'}></label><p class="help">Results screenshot, podium photo or event photo · JPG, PNG or WebP · up to 8 MB. Include your name/bib and placing where possible. Evidence is shared with signed-in sponsors when you save your profile and have a published listing. An image is supporting evidence, not independent verification.</p><button class="button" type="submit">Add to profile</button><p class="help">Save your profile to keep changes.</p><p class="error-text" id="modal-error" role="alert"></p></form>`;}
